# Generated by Django 4.1.7 on 2023-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=122)),
                ('contact_phone', models.CharField(max_length=12)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
