# Generated by Django 4.1.7 on 2023-03-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maya', '0002_remove_contact_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Joinus',
        ),
    ]
