# Generated by Django 4.1.7 on 2023-03-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maya', '0003_rename_contact_joinus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='first_name',
            new_name='name',
        ),
    ]
