# Generated by Django 4.1.7 on 2023-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maya', '0005_rename_name_joinus_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
