# Generated by Django 4.1.7 on 2023-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maya', '0006_alter_joinus_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='id_number',
            new_name='id_num',
        ),
        migrations.RenameField(
            model_name='joinus',
            old_name='comment',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='joinus',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='last_name',
        ),
    ]
